create table pagamento(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
amount decimal(8,3)
)

create table cartao(
id int ,
cardnumber varchar(20),
 FOREIGN KEY (id)
REFERENCES pagamento(id)
)

create table cheque(
id int ,
checknumber varchar(20),
FOREIGN KEY (id)
REFERENCES pagamento(id)
)

select * from pagamento
select * from cartao
select * from cheque
